# Inserts a blank line between shell prompts
add_newline = true

# Change the default prompt format
format = """\
[â•­â•´](238)$env_var \
$all[â•°â”€](238)$character"""

[character]
success_symbol = "[ï•“](238)"
error_symbol = "[ï•“](238)"

[env_var.STARSHIP_SYSTEM]
format = '[$env_value](white)'
variable = "STARSHIP_SYSTEM"
disabled = false

[username]
style_user = "#12191f"
style_root = "#ef2152"
format = "on [ïŠ¾ $user]($style) "
disabled = false
show_always = true

[directory]
truncation_length = 0
truncate_to_repo = false
use_os_path_sep = false
home_symbol = "ï€• ~"
read_only_style = "#ef2152"
read_only = "  ï€£"
format = "at [$path]($style)[$read_only]($read_only_style) "
style = "#12191f"

[git_branch]
format = "on [$symbol$branch]($style) "
truncation_length = 4
truncation_symbol = "â€¦/"
style = "#12191f"

[git_status]
format = '[\( $all_status$ahead_behind \)]($style) '
conflicted = "ğŸ³"
up_to_date = "ï†"
untracked = "ï”©"
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
stashed = "ï£–"
modified = "ï„"
staged = '[+$count](#12191f)'
renamed = "ïª¶"
deleted = "ï€”"
style = "#12191f"

[python]
symbol = "ï Ÿ "
style = "#12191f"
python_binary = ["./venv/Scripts/python", "python", "python3", "python2"]

[nodejs]
symbol = "ï¢˜ "
style = "#12191f"

[java]
symbol = "î‰– "
style = "#12191f"

[package]
symbol = ""
style = "#12191f"
display_private = true
