# Inserts a blank line between shell prompts
add_newline = true

# Change the default prompt format
format = """\
[â•­â•´](238)$env_var \
$all[â•°â”€](238)$character"""

[character]
success_symbol = "[ï•“](238)"
error_symbol = "[ï•“](238)"

[env_var.STARSHIP_SYSTEM]
format = '[$env_value](white)'
variable = "STARSHIP_SYSTEM"
disabled = false

[aws]
format = "on [$symbol $profile]($style) "
symbol = "îŒ½"
style = "#12191f"

[azure]
format = "on [$symbol $subscription]($style) "
style = "#12191f"
disabled = false

[c]
format = "via [$symbol $name ($version )]($style)"
symbol = "î˜"
style = "#12191f"

[cmd_duration]
style = "#12191f"

[cmake]
style = "#12191f"

[container]
format = "[$symbol $name]($style) "
symbol = "ïš¦"
style = "#12191f"

[dart]
symbol = "î˜ "
style = "#12191f"

[directory]
truncation_length = 0
truncate_to_repo = false
use_os_path_sep = false
home_symbol = "ï€• ~"
read_only_style = "#ef2152"
read_only = " ï€£"
format = "at [$path]($style)[$read_only]($read_only_style) "
style = "#12191f"

[docker_context]
format = "via [$symbol $context]($style) "
symbol = "ïŒˆ"
style = "#12191f"

[dotnet]
format = "via [$symbol ($version )]($style)"
symbol = "ï š"
style = "#12191f"

[git_branch]
format = "on [$symbol $branch (-> $remote_branch )]($style)"
truncation_length = 8
truncation_symbol = "â€¦"
symbol = "ï¡"
style = "#12191f"

[git_status]
format = '[\( $all_status$ahead_behind\)]($style) '
conflicted = "ğŸ³ "
up_to_date = "ï† "
untracked = "ï”© "
ahead = "â‡¡${count} "
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count} "
behind = "â‡£${count} "
stashed = "ï£– "
modified = "ï„ "
staged = '[+$count](#12191f) '
renamed = "ïª¶ "
deleted = "ï€” "
style = "#12191f"

[hostname]
format = "on [$ssh_symbol $hostname]($style) "
ssh_symbol = "ïª"
trim_at = ""
style = "#12191f"

[java]
symbol = "î‰– "
style = "#12191f"

[kotlin]
symbol = "î˜´ "
style = "#12191f"

[kubernetes]
format = 'on [$symbol ($user on )($cluster in )$context \($namespace\)]($style) '
symbol = "ï´±"
style = "#12191f"
disabled = false

[nim]
symbol = "ïš¤ "
style = "#12191f"

[nodejs]
style = "#12191f"
not_capable_style = "#ef2152"

[package]
symbol = ""
style = "#12191f"
display_private = true

[python]
symbol = "ï Ÿ "
style = "#12191f"
python_binary = ["./venv/Scripts/python", "python", "python3", "python2"]

[username]
style_user = "#12191f"
style_root = "#ef2152"
format = "on [ïŠ¾ $user]($style) "
disabled = false
show_always = true